logging:
  level:
    com.example.wirelesshome: INFO
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/device"
    username: sonar
    password: sonar
  jpa:
    hibernate:
      ddl-auto: update
scheduler:
  url: "http://localhost:8070/"
