logging:
  level:
    com.example.wirelesshome: INFO
spring:
  datasource:
    url: "jdbc:h2:mem:device"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
scheduler:
  url: "localhost:8070"